### ISSUE TITLE
按键显示出错

### ISSUE THREAD

**Issue by kanglcn** [olOwOlo/hugo-theme-even#235]
<kbd>Shift</kbd> 显示为 Shift

**Comment by panda-z** [comment]
Can't reproduce with the latest version of Hugo (0.69.0).

**Comment by kanglcn** [comment]
My Hugo version is 0.68.3. I will try it again until the manjaro repository update it. Thank you!

**Comment by panda-z** [comment]
Just tested with 0.68.3 and it works well.

**Comment by kanglcn** [comment]
I don't know why but mine can't work well. Here is an example.

[the post](https://kanglcn.github.io/post/vim/)

[the markdown file](https://github.com/kanglcn/blog.content/blob/master/post/2020-04-17-vim.md)

[the html file](https://github.com/kanglcn/kanglcn.github.io/blob/master/post/vim/index.html)

**Comment by panda-z** [comment]
@kanglcn 

Quote from [Hugo docs](https://gohugo.io/getting-started/configuration-markup/#goldmark):
> By default, Goldmark does not render raw HTMLs and potentially dangerous links. If you have lots of inline HTML and/or JavaScript, you may need to turn this on.

So you should add the following to your `config.toml`:
```toml
[markup.goldmark.renderer]
  unsafe = true
```

**Comment by kanglcn** [comment]
I tried but it didn't work. Also I get a warning.

> found no layout file for "HTML" for kind "page": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.

**Comment by panda-z** [comment]
@kanglcn 

You may mess up your files. Please double check.

I've created a new site and tested even theme with your markdown file (modified a bit because the date is in future :D ). It generates the correct HTML file.

![image](https://user-images.githubusercontent.com/1085992/79569798-e3c0fe00-80ea-11ea-8719-78f524ce7d5b.png)

**Comment by panda-z** [comment]
@kanglcn 

Keep in mind that you shouldn't put the following configurations to the beginning of `config.toml`

```TOML
[markup.goldmark.renderer]
  unsafe = true
```

Because if you do so, all the top-level settings are placed after section `[markup.goldmark.renderer]` and will be treated as second-level settings.

The right way is to place sections after the last top-level item.

**Comment by kanglcn** [comment]
Thank you for your patience!! I find I mistake adding it at wrong place. How stupid I am!

Thanks again for your precious time!!
