### ISSUE TITLE
Request: YouTube social icon

### ISSUE THREAD

**Issue by union-of-love** [olOwOlo/hugo-theme-even#407]
![Screenshot_20220801_152521](https://user-images.githubusercontent.com/109987721/182158160-1d6b29f2-5e3f-4ac9-98d6-84496f9d8e53.png)

I would love to see a youtube social icon, IcoFont has support for it, but I'm too much of a noob to understand how to add it.

Could you please add it?

Thank you! :)

**Comment by sumodirjo** [comment]
Hi @union-of-love ,
I created #409 as sample. I think you only need to add Youtube link in the configuration since the parameter will be iterated by this code https://github.com/olOwOlo/hugo-theme-even/blob/564697987de962672112b910422682eb6f9c26ba/layouts/partials/footer.html#L2

Without waiting for #409 to be merged you can just add the sample on the PR to your site config
